### ISSUE TITLE
Unable to deploy repo to students from Learn.co/curriculum

### ISSUE THREAD

**Issue by canikwe** [learn-co-curriculum/activerecord-yelp-exercises#3]
Received the following error when trying to deploy this lab:

Source Repo Does Not Exist ❌ 
Reason For Failure: Fatal: Couldn't Find Remote Ref Refs/Heads/Pin-Ar-Version Unexpected End Of Command Stream

Error Information from deployment summary email:

**Deploy error**
DeployRepo::SourceRepoNotFoundError: fatal: Couldn't find remote ref refs/heads/pin-ar-version Unexpected end of command stream
**Root error**
DeployRepo::GitCommandError

**Backtrace**
/var/app/releases/20191127160104/app/services/curriculum/deploy_repo.rb:152:in `block in run'
/usr/local/rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/open3.rb:205:in `popen_run'
/usr/local/rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/open3.rb:95:in `popen3'
/var/app/releases/20191127160104/app/services/curriculum/deploy_repo.rb:144:in `run'
/var/app/releases/20191127160104/app/services/curriculum/deploy_repo.rb:160:in `block in pull_source_repo'
/var/app/releases/20191127160104/app/services/curriculum/deploy_repo.rb:160:in `each'
/var/app/releases/20191127160104/app/services/curriculum/deploy_repo.rb:160:in `pull_source_repo'
/var/app/releases/20191127160104/app/services/curriculum/deploy_repo.rb:37:in `block (2 levels) in <class:DeployRepo>'
/usr/local/rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tmpdir.rb:89:in `mktmpdir'
/var/app/releases/20191127160104/app/services/curriculum/deploy_repo.rb:35:in `block in <class:DeployRepo>'
/var/app/releases/20191127160104/app/services/base_service.rb:223:in `instance_eval'
/var/app/releases/20191127160104/app/services/base_service.rb:223:in `call'
/var/app/releases/20191127160104/app/services/base_service.rb:197:in `block in execute_with_metrics'
/var/app/releases/20191127160104/app/wrappers/statsd_wrapper.rb:16:in `timing_with_block'
/var/app/releases/20191127160104/app/services/base_service.rb:195:in `execute_with_metrics'
/var/app/releases/20191127160104/app/services/base_service.rb:102:in `execute'
/var/app/releases/20191127160104/app/services/curriculum/deploy_assigned_repo.rb:28:in `block in <class:DeployAssignedRepo>'
/var/app/releases/20191127160104/app/services/base_service.rb:223:in `instance_eval'
/var/app/releases/20191127160104/app/services/base_service.rb:223:in `call'
/var/app/releases/20191127160104/app/services/base_service.rb:197:in `block in execute_with_metrics'
/var/app/releases/20191127160104/app/wrappers/statsd_wrapper.rb:16:in `timing_with_block'
/var/app/releases/20191127160104/app/services/base_service.rb:195:in `execute_with_metrics'
/var/app/releases/20191127160104/app/services/base_service.rb:102:in `execute'
/var/app/releases/20191127160104/app/workers/deploy_assigned_repo_worker.rb:8:in `execute_service'
/var/app/releases/20191127160104/app/workers/base_worker.rb:8:in `block in work'
/var/app/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/var/app/releases/20191127160104/app/workers/base_worker.rb:7:in `work'
/var/app/shared/vendor/bundle/ruby/2.5.0/bundler/gems/sneakers-396c63b521be/lib/sneakers/worker.rb:59:in `block (3 levels) in do_work'
/var/app/shared/vendor/bundle/ruby/2.5.0/bundler/gems/sneakers-396c63b521be/lib/sneakers/metrics/statsd_metrics.rb:14:in `timing'
/var/app/shared/vendor/bundle/ruby/2.5.0/bundler/gems/sneakers-396c63b521be/lib/sneakers/worker.rb:55:in `block (2 levels) in do_work'
/usr/local/rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
/usr/local/rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
/var/app/shared/vendor/bundle/ruby/2.5.0/bundler/gems/sneakers-396c63b521be/lib/sneakers/worker.rb:54:in `block in do_work'
/var/app/shared/vendor/bundle/ruby/2.5.0/gems/thread-0.1.7/lib/thread/pool.rb:56:in `execute'
/var/app/shared/vendor/bundle/ruby/2.5.0/gems/thread-0.1.7/lib/thread/pool.rb:404:in `block (2 levels) in spawn_thread'
/var/app/shared/vendor/bundle/ruby/2.5.0/gems/thread-0.1.7/lib/thread/pool.rb:371:in `loop'
/var/app/shared/vendor/bundle/ruby/2.5.0/gems/thread-0.1.7/lib/thread/pool.rb:371:in `block in spawn_thread'
/var/app/shared/vendor/bundle/ruby/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'

**Comment by canikwe** [comment]
@rrcobb

**Comment by canikwe** [comment]
Resolved. Per Maxwell Benton, "The issue was due to a misalignment in commit histories on the solution"
